-- MySQL Script generated by MySQL Workbench
-- 09/04/18 19:45:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `escola` ;

-- -----------------------------------------------------
-- Table `escola`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`alunos` (
  `matricula` VARCHAR(255) NOT NULL COMMENT '',
  `nome` VARCHAR(255) NULL COMMENT '',
  `dataNascimento` VARCHAR(255) NULL COMMENT '',
  `naturalidade` VARCHAR(45) NULL COMMENT '',
  `nacionalidade` VARCHAR(45) NULL COMMENT '',
  `raca` VARCHAR(45) NULL COMMENT '',
  `sexo` CHAR(1) NULL COMMENT '',
  `estado_civil` VARCHAR(45) NULL COMMENT '',
  `rg` VARCHAR(45) NULL COMMENT '',
  `cpf` VARCHAR(45) NULL COMMENT '',
  `orgao_exp` VARCHAR(45) NULL COMMENT '',
  `data_emissao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`matricula`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`Contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`Contatos` (
  `matricula` VARCHAR(255) NOT NULL COMMENT '',
  `contato` VARCHAR(50) NOT NULL COMMENT '',
  `tipo_contato` ENUM('EMAIL', 'TELEFONE', 'CELULAR') NULL COMMENT '',
  `dono` ENUM('ALUNO', 'RESPONSÁVEL') NULL COMMENT '',
  PRIMARY KEY (`contato`, `matricula`)  COMMENT '',
  INDEX `fk_Contatos_alunos_idx` (`matricula` ASC)  COMMENT '',
  CONSTRAINT `fk_Contatos_alunos`
    FOREIGN KEY (`matricula`)
    REFERENCES `escola`.`alunos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`Endereco` (
  `matricula` VARCHAR(255) NOT NULL COMMENT '',
  `logradouro` VARCHAR(255) NULL COMMENT '',
  `numero` VARCHAR(6) NULL COMMENT '',
  `complemento` VARCHAR(45) NULL COMMENT '',
  `cidade` VARCHAR(45) NULL COMMENT '',
  `uf` VARCHAR(2) NULL COMMENT '',
  `cep` VARCHAR(45) NULL COMMENT '',
  `pais` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`matricula`)  COMMENT '',
  CONSTRAINT `fk_Endereco_alunos1`
    FOREIGN KEY (`matricula`)
    REFERENCES `escola`.`alunos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`filiacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`filiacao` (
  `matricula` VARCHAR(255) NOT NULL COMMENT '',
  `pai` VARCHAR(255) NULL COMMENT '',
  `mae` VARCHAR(255) NULL COMMENT '',
  `cpf_pai` VARCHAR(45) NULL COMMENT '',
  `cpf_mae` VARCHAR(45) NULL COMMENT '',
  `rg_pai` VARCHAR(45) NULL COMMENT '',
  `rg_mae` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`matricula`)  COMMENT '',
  CONSTRAINT `fk_filiacao_alunos1`
    FOREIGN KEY (`matricula`)
    REFERENCES `escola`.`alunos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`ensino` (
  `idEnsino` VARCHAR(10) NOT NULL COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idEnsino`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`modalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`modalidades` (
  `idEnsino` VARCHAR(10) NOT NULL COMMENT '',
  `idModalidade` VARCHAR(10) NOT NULL COMMENT '',
  `descricao` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`idModalidade`, `idEnsino`)  COMMENT '',
  INDEX `fk_modalidades_ensino1_idx` (`idEnsino` ASC)  COMMENT '',
  CONSTRAINT `fk_modalidades_ensino1`
    FOREIGN KEY (`idEnsino`)
    REFERENCES `escola`.`ensino` (`idEnsino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`cursos` (
  `idEnsino` VARCHAR(10) NOT NULL COMMENT '',
  `idModalidade` VARCHAR(10) NOT NULL COMMENT '',
  `idCurso` VARCHAR(10) NOT NULL COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idCurso`, `idEnsino`, `idModalidade`)  COMMENT '',
  INDEX `fk_cursos_modalidades1_idx` (`idModalidade` ASC, `idEnsino` ASC)  COMMENT '',
  CONSTRAINT `fk_cursos_modalidades1`
    FOREIGN KEY (`idModalidade` , `idEnsino`)
    REFERENCES `escola`.`modalidades` (`idModalidade` , `idEnsino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`valores_vigentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`valores_vigentes` (
  `idCurso` VARCHAR(10) NOT NULL COMMENT '',
  `idEnsino` VARCHAR(10) NOT NULL COMMENT '',
  `idModalidade` VARCHAR(10) NOT NULL COMMENT '',
  `valor` FLOAT NULL COMMENT '',
  PRIMARY KEY (`idCurso`, `idEnsino`, `idModalidade`)  COMMENT '',
  CONSTRAINT `fk_valores_vigentes_cursos1`
    FOREIGN KEY (`idCurso` , `idEnsino` , `idModalidade`)
    REFERENCES `escola`.`cursos` (`idCurso` , `idEnsino` , `idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`contratos` (
  `numContrato` VARCHAR(255) NOT NULL COMMENT '',
  `matricula` VARCHAR(255) NOT NULL COMMENT '',
  `idCurso` VARCHAR(10) NOT NULL COMMENT '',
  `idEnsino` VARCHAR(10) NOT NULL COMMENT '',
  `idModalidade` VARCHAR(10) NOT NULL COMMENT '',
  `valorMensalidade` FLOAT NULL COMMENT '',
  `diaVencimento` INT NULL COMMENT '',
  `statusContrato` ENUM('ATV', 'CAN') NULL COMMENT '',
  PRIMARY KEY (`numContrato`, `matricula`, `idCurso`, `idEnsino`, `idModalidade`)  COMMENT '',
  INDEX `fk_contratos_alunos1_idx` (`matricula` ASC)  COMMENT '',
  INDEX `fk_contratos_cursos1_idx` (`idCurso` ASC, `idEnsino` ASC, `idModalidade` ASC)  COMMENT '',
  CONSTRAINT `fk_contratos_alunos1`
    FOREIGN KEY (`matricula`)
    REFERENCES `escola`.`alunos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_cursos1`
    FOREIGN KEY (`idCurso` , `idEnsino` , `idModalidade`)
    REFERENCES `escola`.`cursos` (`idCurso` , `idEnsino` , `idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`grade` (
  `idCurso` VARCHAR(10) NOT NULL COMMENT '',
  `idEnsino` VARCHAR(10) NOT NULL COMMENT '',
  `idModalidade` VARCHAR(10) NOT NULL COMMENT '',
  `anoGrade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCurso`, `idEnsino`, `idModalidade`, `anoGrade`)  COMMENT '',
  INDEX `fk_grade_cursos1_idx` (`idCurso` ASC, `idEnsino` ASC, `idModalidade` ASC)  COMMENT '',
  CONSTRAINT `fk_grade_cursos1`
    FOREIGN KEY (`idCurso` , `idEnsino` , `idModalidade`)
    REFERENCES `escola`.`cursos` (`idCurso` , `idEnsino` , `idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`disciplinas` (
  `idDisciplina` VARCHAR(5) NOT NULL COMMENT '',
  `nomeDisciplina` VARCHAR(45) NULL COMMENT '',
  `tecnica` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idDisciplina`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`matrizCurricular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`matrizCurricular` (
  `idCurso` VARCHAR(10) NOT NULL COMMENT '',
  `idEnsino` VARCHAR(10) NOT NULL COMMENT '',
  `idModalidade` VARCHAR(10) NOT NULL COMMENT '',
  `anoGrade` INT NOT NULL COMMENT '',
  `idDisciplina` VARCHAR(5) NOT NULL COMMENT '',
  `ch` INT NULL COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idCurso`, `idEnsino`, `idModalidade`, `anoGrade`, `idDisciplina`)  COMMENT '',
  INDEX `fk_matrizCurricular_disciplinas1_idx` (`idDisciplina` ASC)  COMMENT '',
  INDEX `fk_matrizCurricular_grade1_idx` (`idCurso` ASC, `idEnsino` ASC, `idModalidade` ASC, `anoGrade` ASC)  COMMENT '',
  CONSTRAINT `fk_matrizCurricular_disciplinas1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `escola`.`disciplinas` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matrizCurricular_grade1`
    FOREIGN KEY (`idCurso` , `idEnsino` , `idModalidade` , `anoGrade`)
    REFERENCES `escola`.`grade` (`idCurso` , `idEnsino` , `idModalidade` , `anoGrade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`grades_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`grades_alunos` (
  `matricula` VARCHAR(255) NOT NULL COMMENT '',
  `idCurso` VARCHAR(10) NOT NULL COMMENT '',
  `idEnsino` VARCHAR(10) NOT NULL COMMENT '',
  `idModalidade` VARCHAR(10) NOT NULL COMMENT '',
  `anoGrade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`matricula`, `idCurso`, `idEnsino`, `idModalidade`, `anoGrade`)  COMMENT '',
  INDEX `fk_grades_alunos_grade1_idx` (`idCurso` ASC, `idEnsino` ASC, `idModalidade` ASC, `anoGrade` ASC)  COMMENT '',
  CONSTRAINT `fk_grades_alunos_alunos1`
    FOREIGN KEY (`matricula`)
    REFERENCES `escola`.`alunos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_alunos_grade1`
    FOREIGN KEY (`idCurso` , `idEnsino` , `idModalidade` , `anoGrade`)
    REFERENCES `escola`.`grade` (`idCurso` , `idEnsino` , `idModalidade` , `anoGrade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`recebimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`recebimentos` (
  `idRecibo` VARCHAR(50) NOT NULL COMMENT '',
  `matricula` VARCHAR(255) NULL COMMENT '',
  `mesReferencia` INT NULL COMMENT '',
  `anoReferencia` INT NULL COMMENT '',
  `dtVencimento` DATE NULL COMMENT '',
  `dtPagamento` DATE NULL COMMENT '',
  `valorMensalidade` FLOAT NULL COMMENT '',
  `valorMulta` FLOAT NULL COMMENT '',
  PRIMARY KEY (`idRecibo`)  COMMENT '',
  INDEX `fk_recebimentos_alunos1_idx` (`matricula` ASC)  COMMENT '',
  CONSTRAINT `fk_recebimentos_alunos1`
    FOREIGN KEY (`matricula`)
    REFERENCES `escola`.`alunos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
